name: Build

on:
  push:
    branches:
      - master
  pull_request:

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get version
      run: |
        VERSION=`grep VERSION src/config.h | awk '{print $3}' | tr -d '"'`
        echo VERSION=${VERSION} | tee -a ${GITHUB_ENV}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.REGISTRY }}/${{ github.repository }}
        tags: |
          type=raw,value=latest
          type=pep440,pattern={{version}},value=${{ env.VERSION }}
        labels: |
          org.opencontainers.image.version=${{ env.VERSION }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: docker/
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

